name: Plan

on: [push]

jobs:
  Plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16"

    - name: Run hclfmt get
      run: GO111MODULE=on go get github.com/hashicorp/hcl/v2/cmd/hclfmt

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Lint hclfmt
      run: cd iox && make lint

    - name: Run Plan
      run: |
        cd iox && echo "y" | make plan
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        cd iox && echo "y" | make publish-iox LAST9_API_KEY={{secrets.LAST9_API_KEY}} REPO_NAME=${{github.repository}}
